# Generated by Django 4.2.21 on 2025-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fv_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='algorithms'),
        ),
    ]
