# Generated by Django 4.2.21 on 2025-06-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fv_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='role',
        ),
    ]
