# Generated by Django 4.2.21 on 2025-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fv_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='snapshot_alg_name',
            field=models.CharField(default='PLACEHOLDER', max_length=255),
        ),
    ]
