# Generated by Django 4.2.21 on 2025-07-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fv_analysis', '0002_execution_snapshot_alg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='requires_two_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='secondary_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_execs', to='fv_analysis.file'),
        ),
    ]
