"""
Django settings for algovision project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import ssl

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Files are now saved in my OneDrive folder on my computer
MEDIA_ROOT = config('DJANGO_MEDIA_ROOT', default='/app/media')

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on activity


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    h.strip()
    for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
    if h.strip()
]

_csrf_origins_raw = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in _csrf_origins_raw.split(',')
    if o.strip()
]

# Behind Caddy/nginx: set SECURE_PROXY_SSL=True in production .env
SECURE_PROXY_SSL = config('SECURE_PROXY_SSL', default=False, cast=bool)
if SECURE_PROXY_SSL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # If you're enabling HSTS behind a TLS-terminating proxy, preload is usually desired.
    # You can still disable it explicitly via SECURE_HSTS_PRELOAD=False.
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'

# Max algorithm subprocess runtime (seconds). 0 = unlimited (not recommended in production).
ALGORITHM_SUBPROCESS_TIMEOUT = config(
    'ALGORITHM_SUBPROCESS_TIMEOUT', default=3600, cast=int)

# When enabled, Celery logs will include a tail of algorithm stdout/stderr even on success.
# Keep disabled in production unless needed (logs can contain user data).
ALGORITHM_SUBPROCESS_LOG_TAILS = config(
    'ALGORITHM_SUBPROCESS_LOG_TAILS', default=False, cast=bool)

# Algorithm subprocess sandboxing (best-effort; Linux setrlimit only).
# These limits mitigate fork-bombs / FD exhaustion / some OOM cases, but do not
# provide filesystem or network isolation.
ALGORITHM_SUBPROCESS_RLIMIT_CPU_SECONDS = config(
    "ALGORITHM_SUBPROCESS_RLIMIT_CPU_SECONDS", default=500, cast=int
)
# Virtual memory cap for the algorithm child process (RLIMIT_AS). TensorFlow/Keras +
# scipy/sklearn imports often need several GiB; 2GiB caused MemoryError on import.
# Set to 0 in .env to disable this limit (rely on container cgroup / host RAM only).
ALGORITHM_SUBPROCESS_RLIMIT_AS_MB = config(
    "ALGORITHM_SUBPROCESS_RLIMIT_AS_MB", default=8192, cast=int
)
ALGORITHM_SUBPROCESS_RLIMIT_FSIZE_MB = config(
    "ALGORITHM_SUBPROCESS_RLIMIT_FSIZE_MB", default=512, cast=int
)
ALGORITHM_SUBPROCESS_RLIMIT_NOFILE = config(
    "ALGORITHM_SUBPROCESS_RLIMIT_NOFILE", default=256, cast=int
)
ALGORITHM_SUBPROCESS_RLIMIT_NPROC = config(
    "ALGORITHM_SUBPROCESS_RLIMIT_NPROC", default=128, cast=int
)
# Positive values make the subprocess *less* CPU-favored.
ALGORITHM_SUBPROCESS_NICE = config("ALGORITHM_SUBPROCESS_NICE", default=5, cast=int)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': config('LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'axes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Content Security Policy (CSP)
# Start strict; relax only as needed for required third-party assets.
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_ANCESTORS = ("'none'",)

ROOT_URLCONF = 'algovision.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Check that this is in your root directory and contains your templates
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'algovision.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST', default='db'),
        'PORT': config('DATABASE_PORT', default='3306'),
    }
}

# Allow running management commands/tests without MySQL client libs installed.
# Production (Docker/CI) should still provide mysqlclient + DB env vars.
try:
    import MySQLdb  # type: ignore  # noqa: F401
except Exception:
    if config("DJANGO_USE_SQLITE_FALLBACK", default=DEBUG, cast=bool):
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": str(BASE_DIR / "db.sqlite3"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.password_validators.HaveIBeenPwnedPasswordValidator',
        'OPTIONS': {
            'enabled': config('HIBP_CHECK_ENABLED', default=True, cast=bool),
            'timeout_seconds': config('HIBP_TIMEOUT_SECONDS', default=3, cast=int),
            'hibp_api_base_url': config('HIBP_API_BASE_URL', default='https://api.pwnedpasswords.com'),
        },
    },
]

# django-axes (login throttling)
# Using defaults that are usually safe: lockout at limit, reset on success.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_ENABLED = config('AXES_ENABLED', default=True, cast=bool)
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=5, cast=int)
AXES_COOLOFF_TIME = config('AXES_COOLOFF_TIME', default=1, cast=int)  # hours
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = 'username'
AXES_VERBOSE = config('AXES_VERBOSE', default=False, cast=bool)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

DATE_INPUT_FORMATS = [
    "%Y-%m-%d",  # HTML5 date input
    "%d/%m/%Y",  # Spanish manual input
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/app/static'
STATICFILES_DIRS = [BASE_DIR / "static"]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery settings
_redis_url = config('REDIS_URL', default='redis://redis:6379/0')
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url

if _redis_url.startswith('rediss://') or config('REDIS_SSL', default=False, cast=bool):
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        'ssl': {
            'ssl_cert_reqs': ssl.CERT_NONE  # o ssl.CERT_REQUIRED si tienes el certificado
        }
    }
else:
    CELERY_BROKER_TRANSPORT_OPTIONS = {}
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
