from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from analysis.views import (
    MediaForwardAuthView,
    HomepageView,
    FileManagerView,
    AnalysisView,
    RenameFileView,
    ResultsView,
    DownloadOutputView,
    ManageRequirementsView,
    RequirementsJSONView,
    DownloadRequirementsView,
    UploadRequirementsView,
    CreateProjectView,
    ManageProjectsView,
    UpdateProjectView,
    DeleteProjectView,
    CreateAlgorithmView,
    ManageAlgorithmsView,
    UpdateAlgorithmView,
    DeleteAlgorithmView,
    ManageUserProjectView,
    CreateUserProjectView,
    UpdateUserProjectView,
    DeleteUserProjectView,
    Custom403View,
    Custom404View)
from accounts.views import LoginHomeView, DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '_caddy/media-auth',
        MediaForwardAuthView.as_view(),
        name='caddy_media_auth',
    ),
    path('', HomepageView.as_view(), name='index'),
    path('accounts/', include('accounts.urls')),
    path('pv-analysis-home/', LoginHomeView.as_view(), name='pv_analysis_home'),
    path('people-analysis-home/', LoginHomeView.as_view(),
         name='people_analysis_home'),
    path('stats-analysis-home/', LoginHomeView.as_view(),
         name='stats_analysis_home'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('files/', FileManagerView.as_view(), name='file_manager'),
    path('files/rename/<int:file_id>/',
         RenameFileView.as_view(), name='rename_file'),
    path('analysis/', AnalysisView.as_view(), name='analysis'),
    path('results/', ResultsView.as_view(), name='results'),
    path('results/download/<int:output_id>/',
         DownloadOutputView.as_view(), name='results_download'),
    path("algorithms/", ManageAlgorithmsView.as_view(),
         name="manage_algorithms"),
    path("algorithms/create/", CreateAlgorithmView.as_view(),
         name="create_algorithm"),
    path("algorithms/delete/<int:pk>/",
         DeleteAlgorithmView.as_view(), name="delete_algorithm"),
    path('algorithms/<int:pk>/edit/',
         UpdateAlgorithmView.as_view(), name='edit_algorithm'),
    path('requirements/', ManageRequirementsView.as_view(),
         name='manage_requirements'),
    path('requirements/json/', RequirementsJSONView.as_view(),
         name='requirements_json'),
    path('requirements/download/', DownloadRequirementsView.as_view(),
         name='download_requirements'),
    path('requirements/upload/', UploadRequirementsView.as_view(),
         name='upload_requirements'),
    path("projects/manage/", ManageProjectsView.as_view(), name="manage_projects"),
    path("projects/create/", CreateProjectView.as_view(), name="create_project"),
    path("projects/edit/<int:pk>/",
         UpdateProjectView.as_view(), name="edit_project"),
    path("projects/delete/<int:pk>/",
         DeleteProjectView.as_view(), name="delete_project"),
    path('projects/manage-projects-permissions/', ManageUserProjectView.as_view(),
         name='manage_projects_permissions'),
    path('user-project/create/', CreateUserProjectView.as_view(),
         name='create_user_project'),
    path('user-project/<int:pk>/edit/',
         UpdateUserProjectView.as_view(), name='edit_user_project'),
    path('user-project/<int:pk>/delete/',
         DeleteUserProjectView.as_view(), name='delete_user_project'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = Custom403View.as_view()
handler404 = Custom404View.as_view()
