# Generated by Django 5.x migration stub

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_algorithm_stable_pkg_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="input_is_dir",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, para entradas de tipo imagen el worker pasa la ruta de una carpeta temporal que contiene el fichero (útil si el script hace os.listdir sobre el argumento). Si no, se pasa la ruta del fichero de imagen.",
                verbose_name="Imagen: pasar carpeta al script",
            ),
        ),
    ]
